name: movie_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
